# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import citadel_pb2 as citadel__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in citadel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CitadelServiceStub(object):
    """── Service Definition ──────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetProfile = channel.unary_unary(
                '/citadel.v1.CitadelService/SetProfile',
                request_serializer=citadel__pb2.SetProfileRequest.SerializeToString,
                response_deserializer=citadel__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.GetCurrentState = channel.unary_unary(
                '/citadel.v1.CitadelService/GetCurrentState',
                request_serializer=citadel__pb2.StateRequest.SerializeToString,
                response_deserializer=citadel__pb2.SystemState.FromString,
                _registered_method=True)
        self.StreamTelemetry = channel.unary_stream(
                '/citadel.v1.CitadelService/StreamTelemetry',
                request_serializer=citadel__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=citadel__pb2.TelemetryPulse.FromString,
                _registered_method=True)


class CitadelServiceServicer(object):
    """── Service Definition ──────────────────────────────────────────────────

    """

    def SetProfile(self, request, context):
        """Mode Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTelemetry(self, request, context):
        """High-Speed Telemetry Stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CitadelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProfile,
                    request_deserializer=citadel__pb2.SetProfileRequest.FromString,
                    response_serializer=citadel__pb2.ProfileResponse.SerializeToString,
            ),
            'GetCurrentState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentState,
                    request_deserializer=citadel__pb2.StateRequest.FromString,
                    response_serializer=citadel__pb2.SystemState.SerializeToString,
            ),
            'StreamTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=citadel__pb2.TelemetryRequest.FromString,
                    response_serializer=citadel__pb2.TelemetryPulse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'citadel.v1.CitadelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('citadel.v1.CitadelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CitadelService(object):
    """── Service Definition ──────────────────────────────────────────────────

    """

    @staticmethod
    def SetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/citadel.v1.CitadelService/SetProfile',
            citadel__pb2.SetProfileRequest.SerializeToString,
            citadel__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/citadel.v1.CitadelService/GetCurrentState',
            citadel__pb2.StateRequest.SerializeToString,
            citadel__pb2.SystemState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/citadel.v1.CitadelService/StreamTelemetry',
            citadel__pb2.TelemetryRequest.SerializeToString,
            citadel__pb2.TelemetryPulse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
